name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Setup NodeJS
        uses: actions/setup-node@v6
      - name: Setup project
        run: make setup
      - name: Test project
        run: make test
      - name: Lint project
        run: make lint
      - name: Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
      - run: echo "🍏 This job's status is ${{ job.status }}."
