name: main
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
    working-directory: ./project
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Setup project
        run: make setup
      - run: echo "🍏 This job's status is ${{ job.status }}."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test project
        run: make test
      - run: echo "🍏 This job's status is ${{ job.status }}."
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint project
        run: make lint
      - run: echo "🍏 This job's status is ${{ job.status }}."
